name: NASA Project CI
on: 
  push:
    branches: [ master ]
  pull_request:  
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install react@17.0.1 react-dom@17.0.1 react-scripts@5.0.0 react-router-dom@5.2.0 arwes@1.0.0-alpha.5 
      - run: npm run build --prefix client     
